In [1]:
import numpy as np

In [3]:
arr=np.array([10,12,14])

In [4]:
arr[0]

10

In [5]:
arr[1]

12

In [6]:
arr2D = np.array([[12,15],[34,55],[18,44],[90,80]])

In [7]:
arr2D[0][1]

15

In [8]:
arr2D[1][0]

34

In [10]:
arr.ndim

1

In [11]:
arr2D.ndim

2

In [13]:
arr=np.array([10,12,14],dtype = np.float64)
arr

array([10., 12., 14.])

In [16]:
print(arr2D.shape)
arr2D

(4, 2)


array([[12, 15],
       [34, 55],
       [18, 44],
       [90, 80]])

In [19]:
l = range(5)
print(l[0])
print(l[1])
print(l[2])
print(l[3])
print(l[4])
np.arange(5)

0
1
2
3
4


array([0, 1, 2, 3, 4])

In [21]:
arr2D.reshape(2,4)

array([[12, 15, 34, 55],
       [18, 44, 90, 80]])

In [24]:
print(arr.min())
print(arr.max())
arr.sum()

10.0
14.0


36.0

In [27]:
print(arr2D)
print(arr2D.sum(axis=0))
print(arr2D.sum(axis=1))


[[12 15]
 [34 55]
 [18 44]
 [90 80]]
[154 194]
[ 27  89  62 170]


In [31]:
print(np.sqrt(arr))
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))

[3.16227766 3.46410162 3.74165739]
1.632993161855452
12.0
12.0


In [34]:
a = np.array([[10,11],[14,15]])
b = np.array([[45,1],[55,17]])
print(a+b,'\n')
print(a*b,'\n')
print(a/b,'\n')
print(a.dot(b))

[[55 12]
 [69 32]] 

[[450  11]
 [770 255]] 

[[ 0.22222222 11.        ]
 [ 0.25454545  0.88235294]] 

[[1055  197]
 [1455  269]]
